name: dart_azure_ad_sign_in
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/Pat992/dart_azure_ad_sign_in
repository: https://github.com/Pat992/dart_azure_ad_sign_in

environment:
  sdk: '>=2.18.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
